services:
  - type: web
    name: sistema-pautas
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install
      npm run build
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    healthCheckTimeout: 100
    healthCheckInterval: 15
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
    envVars:
      - key: RENDER
        value: "true"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 8000
      - key: UPLOAD_FOLDER
        value: /uploads
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sistema_pautas_db
          property: connectionString

databases:
  - name: sistema_pautas_db
    databaseName: sistema_pautas
    user: sistema_pautas_user
