services:
  - type: web
    name: sistema-pautas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    healthCheckTimeout: 100
    healthCheckInterval: 15
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: PORT
        value: 8000
      - key: UPLOAD_FOLDER
        value: /uploads
